<?php
$title = $this->translate('Doctrine Viewer');
?>

<h3 class="page-header"><?php echo $this->translate($title) ?></h3>

<?php if(count($metadatas) > 0): ?>
    <ol>
        <?php foreach ($metadatas as $metadata) :?>
            <li>
                <a href="<?php echo $this->url('dv/entity', array(), array('query' => array('class' => $metadata->getName()))) ?>">
                    <?php echo $this->escapeHtml($metadata->getName()) ?>
                </a>
            </li>
        <?php endforeach ?>
    </ol>
<?php endif ?>